export default {
  primary:       '#0a0a0a',
  white:         '#FFFFFF',
  background:    '#F5F5F5',
  surface:       '#FFFFFF',
  border:        '#E0E0E0',
  borderFocus:   '#AAAAAA',
  textPrimary:   '#0a0a0a',
  textSecondary: '#666666',
  textMuted:     '#999999',
  textHint:      '#BBBBBB',
  error:         '#EF4444',
  success:       '#22C55E',
  successBg:     '#DCFCE7',
  inputBg:       '#FFFFFF',
  subtleBg:      '#F7F7F7',
  googleRed:     '#EA4335',
  tabActive:     '#0a0a0a',
  tabInactive:   '#999999',
  tabBorder:     '#0a0a0a',
  divider:       '#E0E0E0',
};