// src/constants/termsOfUse.js
// The Terms of Use, shipped IN the app rather than fetched from the website.
//
// The privacy policy is a WebView over ailernova.in because that page exists and
// is the source of truth — a copy in the bundle would go stale the moment the
// site was edited. There is no terms page to point at (SignupScreen's comment
// records the five URLs that 404), so the choice is between shipping the text or
// continuing to ask students to accept a document nobody can read.
//
// Shipping it means the version a student agreed to is the version in the build
// they agreed on, which is the right property for a consent document. It also
// means EFFECTIVE_DATE must be bumped whenever the wording changes, and the app
// must ship for the change to reach anyone.
//
// ⚠ DRAFTED, NOT REVIEWED. This was written to fill a gap that was blocking
// Play's Data Safety review, and it describes what the app actually does today —
// but it has not been read by a lawyer. India's DPDP Act has specific
// requirements around processing children's data that this document acknowledges
// rather than satisfies (see the age-gate item on the bug list), and the
// governing-law and liability clauses in particular are the ones a lawyer would
// change first.

export const TERMS_EFFECTIVE_DATE = '5 September 2026';

// Rendered inside PolicyModal's WebView. Self-contained: no external stylesheet,
// no webfont, no network — it has to render on a phone with no connection, which
// is exactly when someone reads terms they have already agreed to.
export const TERMS_HTML = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }
  body { margin: 0; padding: 20px 18px 44px; background: #FFFFFF; color: #111111;
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         font-size: 15px; line-height: 1.62; }
  h1 { font-size: 21px; letter-spacing: -0.02em; margin: 0 0 4px; }
  .eff { color: #666666; font-size: 13px; margin: 0 0 22px; }
  h2 { font-size: 15.5px; margin: 26px 0 7px; letter-spacing: -0.01em; }
  p, li { margin: 0 0 11px; }
  ul { padding-left: 20px; margin: 0 0 11px; }
  strong { font-weight: 700; }
  a { color: #8A6A00; }
  .note { background: #F7F7F8; border: 1px solid rgba(17,17,17,0.08);
          border-radius: 12px; padding: 12px 14px; margin: 18px 0; font-size: 14px; }
</style>
</head><body>

<h1>Terms of Use</h1>
<p class="eff">Effective ${TERMS_EFFECTIVE_DATE}</p>

<p>These terms cover your use of the Ailernova app and the services in it. By
creating an account you agree to them. If you do not agree, please do not use
the app.</p>

<h2>1. Who may use Ailernova</h2>
<p>Ailernova is built for school students, and most of the people using it are
under 18. If you are under 18, you may use Ailernova only with the knowledge and
agreement of a parent or guardian, and they agree to these terms on your behalf.</p>
<p>You need an account to use most of the app. Keep your password to yourself —
anything done from your account is treated as done by you. Tell us at
saurabh@ailernova.com if you think someone else has access to it.</p>

<h2>2. What you get</h2>
<p>A free account includes Brain Gym, the Arena, the games and your Home
dashboard. Lessons, practice, resources, tests and the AI teacher require full
access, which an administrator grants to your account.</p>
<p>We add and change content as the syllabus changes, so what is available will
not always be identical from one month to the next.</p>

<h2>3. The AI teacher, and what it is not</h2>
<p>Lessons, explanations and answers are generated by an AI. It is a study aid,
not a teacher, an examiner or a source of certified results. It can be wrong,
and it can be confidently wrong.</p>
<p><strong>Check anything important against your textbook, your school, or a
teacher before you rely on it</strong> — particularly before an exam. Ailernova
does not guarantee the accuracy of generated content, and does not promise any
particular mark or outcome.</p>

<h2>4. Using the app fairly</h2>
<p>Please do not:</p>
<ul>
  <li>share, resell or republish content from the app;</li>
  <li>use another person's account, or let another person use yours;</li>
  <li>try to break, overload or work around the app's limits or access controls;</li>
  <li>copy content out of the app in bulk, by hand or by script;</li>
  <li>upload anything unlawful, or anything that is not yours to upload.</li>
</ul>
<p>We may suspend or close an account that does these things.</p>

<h2>5. What you upload</h2>
<p>Notes, questions and files you add stay yours. You give us permission to store
and process them so the app can do what you asked — answer a doubt, mark an
attempt, show your progress. We do not sell them, and we do not use them to
advertise to you.</p>

<h2>6. What belongs to us</h2>
<p>The app, its design, and the lessons, questions and explanations in it belong
to Ailernova or to the people we license them from. Your account gives you
permission to use them for your own study, and nothing more.</p>

<h2>7. Payments</h2>
<p>Where a paid plan applies, the price and what it covers are shown before you
pay. Access is granted per account. If a payment fails or is reversed, access may
return to the free tier.</p>

<h2>8. Closing your account</h2>
<p>You can delete your account from Profile at any time. Deletion removes your
personal information on the timeline set out in the Privacy Policy. Some records
are kept where the law requires it.</p>
<p>We may close an account that breaks these terms, or if we stop offering the
service.</p>

<h2>9. Availability</h2>
<p>We try to keep Ailernova running, but we do not promise it will always be
available or uninterrupted. Features may change or be withdrawn. Some parts
depend on services we do not control, and those can fail independently of us.</p>

<h2>10. Limits on liability</h2>
<p>Ailernova is provided as it is. To the extent the law allows, we are not
liable for indirect or consequential loss, or for loss arising from reliance on
AI-generated content. Nothing here limits liability that cannot be limited by
law.</p>

<h2>11. Changes to these terms</h2>
<p>We may update these terms. The effective date at the top changes when we do,
and the current version is always the one in the app. Continuing to use
Ailernova after a change means you accept it.</p>

<h2>12. Governing law</h2>
<p>These terms are governed by the laws of India, and the courts of India have
jurisdiction over any dispute.</p>

<h2>13. Contact</h2>
<p>Ailernova — <a href="mailto:saurabh@ailernova.com">saurabh@ailernova.com</a></p>

<div class="note">
  Read this alongside the <strong>Privacy Policy</strong>, which explains what
  data we collect and how long we keep it. Both are available from your Profile
  at any time, not only at sign-up.
</div>

</body></html>`;

export default TERMS_HTML;
