// src/notes/ChemistryNotes.js

const ChemistryNotes = {

  'Some Basic Concepts of Chemistry': {
    intro: 'Importance, Matter, Laws of Chemical Combination and Stoichiometry',
    sections: [
      {
        title: 'Importance and Scope of Chemistry',
        content: 'Chemistry is central in science and connects with other branches. Its principles are crucial to diverse fields.',
        bullets: [
          'Weather patterns, brain function, computer operations.',
          'Industries like chemical, fertilisers, and pharmaceuticals.',
          'Isolation and synthesis of lifesaving drugs: Cisplatin and Taxol for cancer, AZT for AIDS.',
          'Superconducting ceramics, conducting polymers, optical fibres.',
          'Alternatives for environmentally harmful refrigerants like CFCs; tackling greenhouse gases CH₄ and CO₂.',
        ],
      },
      {
        title: 'Nature of Matter',
        content: 'Anything that has mass and occupies space is termed as matter.',
        bullets: [
          'Solid: particles held close together in an orderly fashion, definite shape and volume.',
          'Liquid: particles close but can move around, definite volume but no definite shape.',
          'Gas: particles far apart with easy movement, neither definite volume nor shape.',
          'States are interconvertible by changing temperature and pressure.',
        ],
      },
      {
        title: 'Classification of Matter',
        bullets: [
          'Pure Substances: same composition throughout — e.g. copper, water, glucose.',
          'Mixtures: variable composition — homogeneous (sugar solution) or heterogeneous (salt + sugar).',
          'Elements: consist of a single type of atom.',
          'Compounds: two or more atoms chemically combined in fixed ratio, with properties distinct from constituent elements.',
        ],
      },
      {
        title: 'Properties of Matter and their Measurement',
        bullets: [
          'Accuracy: agreement of a particular value to the true value.',
          'Precision: closeness of various measurements for the same quantity.',
          'Volume: $1\\text{ L} = 1\\text{ dm}^3 = 10^3\\text{ cm}^3 = 10^{-3}\\text{ m}^3$',
          'Temperature: $K = °C + 273.15$',
          'STP: 0°C (273.15 K) and 1 atm. NTP: 20°C (293.15 K) and 1 atm. SATP: 25°C (298.15 K) and 1 atm.',
          'Density = mass/volume. SI unit: kg/m³; practical: g/cm³.',
        ],
      },
      {
        title: 'SI Units',
        table: {
          headers: ['Physical Quantity', 'SI Unit', 'Symbol'],
          rows: [
            ['Mass', 'Kilogram', 'kg'],
            ['Length', 'Metre', 'm'],
            ['Temperature', 'Kelvin', 'K'],
            ['Amount of substance', 'Mole', 'mol'],
            ['Time', 'Second', 's'],
            ['Electric current', 'Ampere', 'A'],
            ['Luminous intensity', 'Candela', 'cd'],
          ],
        },
      },
      {
        title: 'Laws of Chemical Combinations',
        bullets: [
          'Law of Conservation of Mass (Lavoisier, 1789): mass can neither be created nor destroyed in any physical or chemical change.',
          'Law of Definite Proportions (Proust): a given compound always contains the same elements in the same proportion by mass.',
          'Law of Multiple Proportions (Dalton, 1803): masses of one element combining with fixed mass of another are in ratio of small whole numbers. Example: H₂O and H₂O₂ — oxygen masses 16g and 32g combine with 2g H → ratio 1:2.',
          "Gay Lussac's Law: gases combine in simple ratio of volumes at same T and P. Example: 100 mL H₂ + 50 mL O₂ → 100 mL H₂O vapour (2:1 ratio).",
          "Avogadro's Law (1811): equal volumes of all gases at same T and P contain equal number of molecules.",
        ],
      },
      {
        title: 'Scientific Notation and Significant Figures',
        content: 'Numbers expressed as $N \\times 10^n$ where $N$ ranges from 1.000 to 9.999.',
        bullets: [
          'Large number: $6.022 \\times 10^{23}$ molecules of hydrogen gas.',
          'Small number: $1.66 \\times 10^{-24}$ g (mass of H atom).',
          'Multiplication: multiply coefficients, add exponents. $(5.6 \\times 10^5) \\times (6.9 \\times 10^4) = 3.864 \\times 10^{14}$',
          'Division: divide coefficients, subtract exponents. $(2.7 \\times 10^{-3}) / (5.5 \\times 10^4) = 4.909 \\times 10^{-4}$',
          'Addition/Subtraction: align exponents first.',
          'Significant figures: all non-zero digits, zeros between non-zero digits, trailing zeros in decimals.',
        ],
      },
      {
        title: "Dalton's Atomic Theory",
        bullets: [
          'Democritus (~400 BC) proposed matter consists of small indivisible particles — "a-tomio" (uncuttable).',
          "Dalton published 'A New System of Chemical Philosophy' in 1808.",
          'Matter consists of indivisible atoms.',
          'All atoms of a given element are identical in mass and properties.',
          'Atoms of different elements have distinct masses.',
          'Compounds form when atoms combine in fixed ratios.',
          'Atoms are neither created nor destroyed in chemical reactions.',
          'Limitation: could not explain laws of gaseous volumes.',
        ],
      },
      {
        title: 'Atomic and Molecular Masses',
        content: '$$1\\text{ u} = 1.66056 \\times 10^{-24}\\text{ g}$$ 1 amu = $\\frac{1}{12}$ mass of carbon-12 atom. Current standard: carbon-12 isotope adopted in 1961.',
        bullets: [
          'Hydrogen atom: 1.0078 amu. Oxygen atom: 15.995 amu.',
          'Average atomic mass: accounts for isotopic abundance. Carbon average = 12.011 u (C-12: 98.892%, C-13: 1.108%, C-14: trace).',
          'Molecular mass = sum of atomic masses. CH₄ = 12.011 + 4(1.008) = 16.043 u. H₂O = 2(1.008) + 16.00 = 18.02 u.',
          'Formula mass (ionic compounds): NaCl = 23.0 + 35.5 = 58.5 u.',
        ],
      },
      {
        title: 'Mole Concept and Molar Masses',
        content: 'The mole is the amount of substance containing $6.022 \\times 10^{23}$ entities (Avogadro\'s number $N_A$). $$n = \\frac{w_g}{M_m} = \\frac{V_L(\\text{at STP})}{22.4} = \\frac{x\\text{ particles}}{N_A}$$',
        bullets: [
          '1 mole of CH₄ = 16 g = $6.022 \\times 10^{23}$ molecules = 22.4 L at STP.',
          'Molar mass of H₂O = 18.02 g/mol.',
          'Molar volume at STP (273 K, 1 atm) = 22.4 L. At (273 K, 1 bar) = 22.7 L.',
          'Molar volume calculation: $V = \\frac{nRT}{P} = \\frac{1 \\times 0.082 \\times 273}{1} = 22.4\\text{ L}$',
        ],
      },
      {
        title: 'Percentage Composition',
        content: '$$\\%\\text{ of element} = \\frac{\\text{Mass of element in one molecule}}{\\text{Molecular mass}} \\times 100$$',
        bullets: [
          'Water (H₂O): % H = $(2 \\times 1.008 / 18.02) \\times 100 = 11.18\\%$; % O = $88.79\\%$.',
          'Ethanol (C₂H₅OH): % C = 52.14%, % H = 13.13%, % O = 34.73%.',
          'Used to verify purity, identify formula, and understand compound composition.',
        ],
      },
      {
        title: 'Empirical and Molecular Formula',
        content: 'Empirical formula: simplest whole number ratio of atoms. Molecular formula: actual number of atoms.',
        bullets: [
          'Benzene: empirical = CH, molecular = C₆H₆.',
          'Glucose: empirical = CH₂O, molecular = C₆H₁₂O₆.',
          '$\\text{Molecular formula} = n \\times \\text{Empirical formula}$',
          '$n = \\dfrac{\\text{Molar mass}}{\\text{Empirical formula mass}}$',
        ],
      },
      {
        title: 'Chemical Reactions and Information from Equations',
        table: {
          headers: ['Interpretation', 'N₂(g)', '+', '3H₂(g)', '→', '2NH₃(g)'],
          rows: [
            ['Molecules', '1 molecule', '+', '3 molecules', '→', '2 molecules'],
            ['Moles', '1 mole', '+', '3 moles', '→', '2 moles'],
            ['Mass', '28 g', '+', '6 g', '→', '34 g'],
            ['Volume at STP', '22.4 L', '+', '67.2 L', '→', '44.8 L'],
          ],
        },
      },
      {
        title: 'Stoichiometry and Stoichiometric Calculations',
        content: 'Stoichiometry is the calculation of masses and volumes of reactants and products. Based on balanced chemical equations.',
        bullets: [
          'Limiting reagent: reactant consumed first; limits amount of product formed.',
          'Parts per million (ppm): $= \\frac{\\text{Parts of solute (by mass)}}{\\text{Parts of solution (by mass)}} \\times 10^6$',
          'Molarity (M): moles of solute per litre of solution.',
          'Molality (m): moles of solute per kg of solvent (temperature independent).',
          'Mole fraction: $x_1 = \\frac{n_1}{n_1+n_2}$; sum of all mole fractions = 1.',
          'Mass percent: $= \\frac{\\text{Mass of solute}}{\\text{Mass of solution}} \\times 100$',
          'Dilution: $M_1V_1 = M_2V_2$',
        ],
      },
    ],
  },

  'Structure of Atom': {
    intro: 'Subatomic Particles, Atomic Models, Quantum Numbers and Electronic Configuration',
    sections: [
      {
        title: 'Fundamental Particles of Atom',
        table: {
          headers: ['Particle', 'Mass (amu)', 'Mass (kg)', 'Charge (C)', 'Relative Charge'],
          rows: [
            ['Electron', '0.000546', '$9.109 \\times 10^{-31}$', '$-1.602 \\times 10^{-19}$', '-1'],
            ['Proton', '1.00728', '$1.673 \\times 10^{-27}$', '$+1.602 \\times 10^{-19}$', '+1'],
            ['Neutron', '1.008665', '$1.675 \\times 10^{-27}$', 'Zero', 'Zero'],
          ],
        },
      },
      {
        title: 'Discovery of Sub-Atomic Particles',
        bullets: [
          'Cathode ray experiment: electrons originate from cathode to anode, travel in straight lines, deflect in electric/magnetic fields like negatively charged particles.',
          'J.J. Thomson (1897): measured charge-to-mass ratio of electron. $e/m_e = 1.758820 \\times 10^{11}$ C kg$^{-1}$.',
          "Millikan's oil drop experiment (1906-14): electron charge = $-1.602176 \\times 10^{-19}$ C.",
          'Canal rays: positively charged particles. Smallest = proton from hydrogen (1919).',
          'Neutron: discovered by Chadwick (1932) by bombarding beryllium with alpha particles.',
        ],
      },
      {
        title: 'Atomic Number, Isotopes and Isobars',
        content: 'Atomic number (Z) = number of protons = number of electrons in neutral atom. Mass number (A) = protons + neutrons.',
        bullets: [
          'Isotopes: same Z, different A (different neutrons). Same chemical properties.',
          'H isotopes: Protium (99.985%), Deuterium (0.015%), Tritium (trace).',
          'Carbon isotopes: $^{12}$C (6p,6n), $^{13}$C (6p,7n), $^{14}$C (6p,8n).',
          'Isobars: same A, different Z. Example: $^{14}$C and $^{14}$N.',
        ],
      },
      {
        title: "Thomson's Atomic Model and Limitations",
        content: "Thomson's plum pudding model (1898): atom is a sphere of uniform positive charge with electrons embedded in it.",
        bullets: [
          'Also called raisin pudding or watermelon model.',
          'Explained overall neutrality of the atom.',
          'Nobel Prize in Physics 1906.',
          'Limitations: could not explain existence of dense nucleus, incorrect charge distribution, failed to explain atomic stability and line spectra, inconsistent with Rutherford\'s scattering experiment.',
        ],
      },
      {
        title: "Rutherford's Nuclear Model",
        content: "$\\alpha$-particle scattering experiment:",
        bullets: [
          'Most of an atom is empty space.',
          'All positive charge and most mass concentrated in tiny dense nucleus.',
          'Electrons revolve around nucleus.',
          'Limitation: could not explain atomic spectra; electrons should lose energy and spiral into nucleus.',
        ],
      },
      {
        title: "Bohr's Model of Hydrogen Atom",
        content: "Bohr's postulates:",
        bullets: [
          'Electrons revolve in fixed circular orbits (stationary states) without radiating energy.',
          'Angular momentum is quantised: $mvr = \\frac{nh}{2\\pi}$',
          'Energy of $n$th orbit: $E_n = -2.18 \\times 10^{-18} \\frac{Z^2}{n^2}$ J/atom',
          'Energy emitted/absorbed when electron jumps between orbits: $\\Delta E = E_f - E_i$',
          'Limitation: failed to explain multi-electron atom spectra, Zeeman effect, Stark effect, and chemical bond formation.',
        ],
      },
      {
        title: 'Hydrogen Spectrum',
        content: 'Rydberg formula: $$\\frac{1}{\\lambda} = R\\left(\\frac{1}{n_f^2} - \\frac{1}{n_i^2}\\right)Z^2$$ where $R = 109678$ cm$^{-1}$',
        table: {
          headers: ['Series', 'Transition ($n_i$ → $n_f$)', 'Region'],
          rows: [
            ['Lyman', '$n_i = 2,3,4,...$ → $n_f = 1$', 'UV'],
            ['Balmer', '$n_i = 3,4,5,...$ → $n_f = 2$', 'Visible (VIBGYOR)'],
            ['Paschen', '$n_i = 4,5,6,...$ → $n_f = 3$', 'IR'],
            ['Brackett', '$n_i = 5,6,7,...$ → $n_f = 4$', 'IR'],
            ['Pfund', '$n_i = 6,7,8,...$ → $n_f = 5$', 'Far IR'],
          ],
        },
      },
      {
        title: 'Dual Nature of Matter and Light',
        content: 'Electromagnetic radiation: oscillating electric and magnetic fields perpendicular to each other, travelling at speed of light.',
        bullets: [
          'Wavelength ($\\lambda$): distance of one crest and one trough.',
          'Frequency ($\\nu$): number of waves per second. Unit: Hz (s$^{-1}$).',
          'Wave number: $\\bar{\\nu} = 1/\\lambda$ (cm$^{-1}$).',
          'Speed of light: $c = \\lambda\\nu = 3 \\times 10^8$ m/s.',
          "Planck's quantum theory: energy is quantised. $E = h\\nu$, where $h = 6.626 \\times 10^{-34}$ J·s.",
          'Photoelectric effect: $h\\nu - h\\nu_0 = \\frac{1}{2}mv^2$ (Einstein).',
          'Wave-particle duality: light shows wave properties (interference, diffraction) and particle properties (photoelectric effect).',
        ],
      },
      {
        title: "de Broglie's Relationship",
        content: 'All material particles in motion exhibit wave-like properties: $$\\lambda = \\frac{h}{mv} = \\frac{h}{p}$$',
        bullets: [
          'Lighter, faster particles have measurable wavelengths.',
          'Macroscopic objects: $\\lambda$ too small to detect → particle nature dominant.',
          'Microscopic particles (electrons): dual nature — both wave and particle.',
          'Confirmed by electron diffraction experiments.',
        ],
      },
      {
        title: "Heisenberg's Uncertainty Principle",
        content: '$$\\Delta x \\cdot \\Delta p \\geq \\frac{h}{4\\pi}$$ It is impossible to simultaneously determine both position and momentum of an electron with perfect accuracy.',
      },
      {
        title: 'Quantum Mechanical Model of Atom',
        content: "Schrödinger's wave equation: $\\hat{H}\\psi = E\\psi$ where $\\psi$ = wave function, $|\\psi|^2$ = probability density of finding electron.",
        bullets: [
          'Atomic orbital: 3D region around nucleus with highest probability of finding electrons.',
          'Nodal plane: region where probability = zero.',
          'Radial nodes = $n - l - 1$. Angular nodes = $l$. Total nodes = $n - 1$.',
        ],
      },
      {
        title: 'Quantum Numbers',
        table: {
          headers: ['Quantum Number', 'Symbol', 'Values', 'Describes'],
          rows: [
            ['Principal', '$n$', '$1,2,3,...$', 'Shell distance from nucleus, energy'],
            ['Azimuthal', '$l$', '$0$ to $n-1$', 'Subshell shape (s,p,d,f)'],
            ['Magnetic', '$m_l$', '$-l$ to $+l$', 'Orientation of orbital $(2l+1)$ values'],
            ['Spin', '$m_s$', '$+\\frac{1}{2}, -\\frac{1}{2}$', 'Electron spin direction'],
          ],
        },
      },
      {
        title: 'Shells and Subshells',
        table: {
          headers: ['Shell (n)', 'Subshells (l)', 'Max electrons ($2n^2$)'],
          rows: [
            ['K (n=1)', 's', '2'],
            ['L (n=2)', 's, p', '8'],
            ['M (n=3)', 's, p, d', '18'],
            ['N (n=4)', 's, p, d, f', '32'],
          ],
        },
      },
      {
        title: 'Shapes of s, p and d Orbitals',
        bullets: [
          's-orbital ($l=0$): spherical shape. Expands without losing sphere shape as $n$ increases.',
          'p-orbital ($l=1$): dumbbell shape with two lobes, a node, three orientations ($p_x, p_y, p_z$).',
          'd-orbital ($l=2$): cloverleaf shape with four lobes; one has ring around nucleus; five orientations.',
          'f-orbital ($l=3$): complex shape; seven orientations.',
        ],
      },
      {
        title: 'Aufbau Principle',
        content: 'Electrons fill orbitals in increasing order of energy (increasing $n+l$ value). For same $n+l$, lower $n$ fills first.',
        bullets: [
          'Order: $1s < 2s < 2p < 3s < 3p < 4s < 3d < 4p < 5s < 4d < 5p < 6s < 4f < 5d < 6p < 7s$',
          'In same shell: energy increases $s < p < d < f$.',
        ],
      },
      {
        title: "Pauli's Exclusion Principle and Hund's Rule",
        bullets: [
          "Pauli's Exclusion Principle: no two electrons in an atom can have the same set of four quantum numbers. Maximum 2 electrons per orbital (opposite spins).",
          "Hund's Rule of Maximum Multiplicity: electrons fill degenerate orbitals singly with same spin before pairing begins.",
          'Max electrons: s-subshell = 2, p = 6, d = 10, f = 14.',
          'Half-filled and fully-filled orbitals are extra stable (symmetrical distribution, maximised exchange energy).',
        ],
      },
      {
        title: 'Electronic Configuration of Atoms',
        content: 'Wave function ($\\psi$) locates electron; $\\psi^2$ gives probability (defines one orbital).',
        bullets: [
          'Exceptions to Aufbau: Cr = $[Ar]\\,4s^1 3d^5$ (half-filled d); Cu = $[Ar]\\,4s^1 3d^{10}$ (fully-filled d).',
          'Extra stability due to: symmetric distribution, lower energy, increased exchange energy.',
          'Shielding/screening effect: inner electrons reduce nuclear attraction on outer electrons. Order: s > p > d > f.',
        ],
      },
      {
        title: 'Electronic Configuration Examples',
        table: {
          headers: ['Element', 'Z', 'Electronic Configuration'],
          rows: [
            ['H', '1', '$1s^1$'],
            ['He', '2', '$1s^2$'],
            ['Li', '3', '$1s^2\\,2s^1$'],
            ['C', '6', '$1s^2\\,2s^2\\,2p^2$'],
            ['N', '7', '$1s^2\\,2s^2\\,2p^3$'],
            ['Na', '11', '$[Ne]\\,3s^1$'],
            ['Cr', '24', '$[Ar]\\,4s^1\\,3d^5$'],
            ['Cu', '29', '$[Ar]\\,4s^1\\,3d^{10}$'],
          ],
        },
      },
    ],
  },

  'Classification of Elements and Periodicity in Properties': {
    intro: 'Periodic Table, Electronic Configurations and Periodic Trends',
    sections: [
      {
        title: 'Why Do We Need to Classify Elements?',
        content: 'In 1800: 31 elements known. By 1865: 63. Today: 114 elements. Classification helps organise knowledge, rationalise chemical facts, predict unknown properties.',
      },
      {
        title: 'Brief History of Periodic Table',
        bullets: [
          "Döbereiner's Triads (1829): groups of three elements; middle element's atomic mass ≈ average of other two. Limited to few elements.",
          "de Chancourtois's Cylinder (1862): cylindrical table showing periodic recurrence when elements arranged by atomic weights.",
          "Newlands' Law of Octaves (1866): every 8th element has similar properties. Worked only for lighter elements.",
          "Lothar Meyer (1869): plotted atomic volume vs. atomic weight — periodic patterns observed.",
          "Mendeleev's Periodic Law (1869): properties are periodic function of atomic weight. Left gaps for undiscovered elements; predicted gallium and germanium.",
          "Moseley (1913): atomic number is fundamental, not atomic mass → Modern Periodic Law.",
        ],
      },
      {
        title: 'Modern Periodic Law and Present Form of Periodic Table',
        content: '"The physical and chemical properties of elements are periodic functions of their atomic numbers."',
        bullets: [
          '7 horizontal rows = Periods. 18 vertical columns = Groups.',
          'Group 1: Alkali metals. Group 2: Alkaline earth metals.',
          'Group 15: Pnictogens. Group 16: Chalcogens. Group 17: Halogens. Group 18: Noble gases.',
          'Period 1: 2 elements. Periods 2 & 3: 8 each. Periods 4 & 5: 18 each. Period 6: 32. Period 7: incomplete (32).',
        ],
      },
      {
        title: 'Nomenclature of Elements with Atomic Number > 100',
        content: 'IUPAC systematic naming using numerical roots + "ium":',
        table: {
          headers: ['Digit', 'Root', 'Symbol'],
          rows: [
            ['0', 'nil', 'n'],
            ['1', 'un', 'u'],
            ['2', 'bi', 'b'],
            ['3', 'tri', 't'],
            ['4', 'quad', 'q'],
            ['5', 'pent', 'p'],
            ['6', 'hex', 'h'],
            ['7', 'sept', 's'],
            ['8', 'oct', 'o'],
            ['9', 'enn', 'e'],
          ],
        },
      },
      {
        title: 'IUPAC Official Names (101-110)',
        table: {
          headers: ['Z', 'Name', 'Symbol'],
          rows: [
            ['101', 'Mendelevium', 'Md'],
            ['102', 'Nobelium', 'No'],
            ['103', 'Lawrencium', 'Lr'],
            ['104', 'Rutherfordium', 'Rf'],
            ['105', 'Dubnium', 'Db'],
            ['106', 'Seaborgium', 'Sg'],
            ['107', 'Bohrium', 'Bh'],
            ['108', 'Hassium', 'Hs'],
            ['109', 'Meitnerium', 'Mt'],
            ['110', 'Darmstadtium', 'Ds'],
          ],
        },
      },
      {
        title: 'Electronic Configurations and the Periodic Table',
        bullets: [
          "s-block: Groups 1-2. Outer config: $ns^1, ns^2$. Highly reactive, low IE, lose electrons easily.",
          "p-block: Groups 13-18. Outer config: $ns^2np^1$ to $ns^2np^6$. Noble gases fully filled = low reactivity.",
          "d-block (transition): Groups 3-12. Config: $(n-1)d^{1-10}ns^{0-2}$. Coloured ions, variable oxidation states, catalytic use.",
          "f-block: Lanthanoids (Ce-Lu, 4f) and Actinoids (Th-Lr, 5f). Placed at bottom of table.",
          'General configs — s: $ns^{1,2}$; p: $ns^2np^{1-6}$; d: $(n-1)d^{1-10}ns^{0-2}$; f: $(n-2)f^{1-14}(n-1)d^{0,1}ns^2$',
        ],
      },
      {
        title: 'Atomic Radius',
        bullets: [
          'Across a period (→): decreases due to increasing nuclear charge without addition of new shell.',
          'Down a group (↓): increases due to successive addition of shells.',
          'Noble gases: larger radius than Group 17 due to complete filling and electron-electron repulsion.',
          'van der Waals radius > Metallic radius > Covalent radius.',
        ],
      },
      {
        title: 'Ionic Radius',
        content: 'Isoelectronic species table:',
        table: {
          headers: ['Ion', 'Na⁺', 'Mg²⁺', 'Al³⁺', 'F⁻', 'O²⁻', 'N³⁻'],
          rows: [
            ['Protons', '11', '12', '13', '9', '8', '7'],
            ['Electrons', '10', '10', '10', '10', '10', '10'],
          ],
        },
      },
      {
        title: 'Ionic Radius Trends',
        bullets: [
          'Cation < parent atom: more protons than electrons, increased coulombic force.',
          'Anion > parent atom: more electrons than protons, increased electron-electron repulsion.',
          'Isoelectronic species: more charge on cation → smaller size. More charge on anion → larger size.',
          'Size order: $Al^{3+} < Mg^{2+} < Na^+ < F^- < O^{2-} < N^{3-}$',
        ],
      },
      {
        title: 'Ionisation Enthalpy',
        content: 'Minimum energy to remove most loosely bound electron from isolated gaseous atom: $M(g) + \\text{Energy} \\to M^+(g) + e^-$. $IE_3 > IE_2 > IE_1$.',
        bullets: [
          'Across period (→): increases (nuclear charge increases, atomic radius decreases).',
          'Down group (↓): decreases (atomic radius increases, shielding increases).',
          'Order in period 2: $Li < B < Be < C < O < N < F < Ne$',
          'Shielding effect order: s > p > d > f.',
          'Noble gases: highest IE. Alkali metals: lowest IE.',
        ],
      },
      {
        title: 'Electron Gain Enthalpy',
        content: 'Enthalpy change when extra electron added to neutral gaseous atom: $E(g) + e^- \\to E^-(g)$',
        bullets: [
          'Across period (→): increases (more negative) due to decreasing size and increasing nuclear charge.',
          'Down group (↓): decreases (less negative) due to increasing size.',
          'Cl has more negative EGE than F: small size of F causes more inter-electronic repulsion.',
          'Maximum EGE: Chlorine. Order: Halogen > O > N > metals.',
          '2nd electron gain enthalpy is always positive.',
        ],
      },
      {
        title: 'Electronegativity',
        content: 'Tendency of an atom to attract the shared pair of electrons in a bonded state.',
        bullets: [
          'Increases across period (→); decreases down group (↓).',
          'Most electronegative: F (4.0 Pauling). Least: Cs.',
          'Order: F > O > N > Cl.',
          'Difference from EGE: EGE is energy; electronegativity is tendency (not energy).',
        ],
      },
      {
        title: 'Important Element Facts',
        bullets: [
          'Lightest element: Hydrogen. Lightest metal: Lithium.',
          'Highest density metal: Osmium. Most reactive metal: Caesium.',
          'Most reactive non-metal: Fluorine. Most malleable metal: Gold.',
          'Best electrical conductor: Silver.',
          'Strongest reducing agent (aqueous): Lithium.',
          'Strongest oxidising agent: Fluorine.',
          'Lowest IE: Caesium. Highest IE: Helium.',
          'Highest EGE: Chlorine.',
        ],
      },
      {
        title: 'Periodic Trends Summary',
        table: {
          headers: ['Property', 'Across Period →', 'Down Group ↓'],
          rows: [
            ['Atomic radius', 'Decreases', 'Increases'],
            ['Ionic radius (cation)', 'Decreases', 'Increases'],
            ['Ionisation enthalpy', 'Increases', 'Decreases'],
            ['Electron gain enthalpy', 'More negative', 'Less negative'],
            ['Electronegativity', 'Increases', 'Decreases'],
            ['Metallic character', 'Decreases', 'Increases'],
            ['Non-metallic character', 'Increases', 'Decreases'],
          ],
        },
      },
      {
        title: 'Diagonal Relationship',
        content: 'Similarities between first member of a group and second member of the next higher group (comparable atomic radius and polarising power). Example: Li–Mg, Be–Al, B–Si.',
      },
      {
        title: 'Valence and Element Type',
        table: {
          headers: ['Valence shell electrons', 'Type'],
          rows: [
            ['1, 2, 3', 'Metals'],
            ['4', 'Metalloids'],
            ['5, 6, 7', 'Non-metals'],
            ['8', 'Noble gases'],
          ],
        },
      },
    ],
  },

  'Chemical Bonding and Molecular Structure': {
    intro: 'Ionic, Covalent Bonds, VSEPR and Molecular Orbital Theory',
    sections: [
      {
        title: 'Kössel-Lewis Approach',
        content: "Atoms combine to achieve stable noble gas configuration (octet rule). Electrons are transferred or shared.",
        bullets: [
          'Ionic bond: electron transfer from metal to non-metal.',
          'Covalent bond: electron sharing between non-metals.',
          'Lewis dot structure: valence electrons represented as dots.',
        ],
      },
      {
        title: 'Ionic Bond',
        content: 'Formed by complete transfer of electrons. Example: NaCl. $$Na \\to Na^+ + e^-, \\quad Cl + e^- \\to Cl^-$$',
        bullets: [
          'High melting and boiling points.',
          'Conduct electricity in molten state or solution.',
          'Lattice energy: energy released when ions form crystal lattice.',
          'Born-Haber cycle used to calculate lattice energy.',
        ],
      },
      {
        title: 'Covalent Bond',
        content: 'Formed by sharing of electron pairs between atoms.',
        bullets: [
          'Single bond: one shared pair (e.g. H–H).',
          'Double bond: two shared pairs (e.g. O=O).',
          'Triple bond: three shared pairs (e.g. N≡N).',
          'Bond order = number of shared pairs.',
          'Bond length decreases and bond energy increases with bond order.',
        ],
      },
      {
        title: 'Formal Charge',
        content: '$$\\text{Formal charge} = \\text{Valence electrons} - \\text{Non-bonding electrons} - \\frac{1}{2}\\text{Bonding electrons}$$',
      },
      {
        title: 'VSEPR Theory',
        content: 'Valence Shell Electron Pair Repulsion theory predicts molecular geometry. Electron pairs arrange to minimise repulsion.',
        table: {
          headers: ['Bonding Pairs', 'Lone Pairs', 'Shape', 'Example'],
          rows: [
            ['2', '0', 'Linear (180°)', 'BeCl₂'],
            ['3', '0', 'Trigonal planar (120°)', 'BF₃'],
            ['4', '0', 'Tetrahedral (109.5°)', 'CH₄'],
            ['3', '1', 'Pyramidal (~107°)', 'NH₃'],
            ['2', '2', 'Bent (~104.5°)', 'H₂O'],
            ['5', '0', 'Trigonal bipyramidal', 'PCl₅'],
            ['6', '0', 'Octahedral (90°)', 'SF₆'],
          ],
        },
      },
      {
        title: 'Polarity of Bonds',
        content: 'Bond polarity arises due to difference in electronegativity. Dipole moment: $\\mu = q \\times d$ (unit: Debye, D).',
        bullets: [
          'Non-polar: same atoms (H₂, Cl₂) or symmetric molecules (CO₂, BF₃).',
          'Polar: different atoms with different electronegativities (HCl, H₂O, NH₃).',
        ],
      },
      {
        title: 'Valence Bond Theory (VBT)',
        content: 'Bond forms when orbitals of two atoms overlap. Greater overlap → stronger bond.',
        bullets: [
          'σ bond: head-on overlap, stronger, free rotation.',
          'π bond: lateral overlap, weaker, no free rotation.',
          'sp³ hybridisation: tetrahedral (CH₄, NH₃, H₂O).',
          'sp² hybridisation: trigonal planar (BF₃, C₂H₄).',
          'sp hybridisation: linear (BeCl₂, C₂H₂).',
        ],
      },
      {
        title: 'Molecular Orbital Theory (MOT)',
        content: 'Atomic orbitals combine to form molecular orbitals (MOs) spread over entire molecule.',
        bullets: [
          'Bonding MO: lower energy, electrons stabilise molecule.',
          'Antibonding MO ($\\sigma^*$, $\\pi^*$): higher energy, electrons destabilise.',
          'Bond order = $\\frac{1}{2}$(bonding electrons − antibonding electrons).',
          'Bond order > 0 → stable molecule.',
        ],
      },
      {
        title: 'Hydrogen Bond',
        content: 'Electrostatic attraction between H (bonded to F, O, or N) and electronegative atom of another molecule.',
        bullets: [
          'Intermolecular H-bond: between different molecules (e.g. H₂O — responsible for high boiling point).',
          'Intramolecular H-bond: within same molecule (e.g. o-nitrophenol).',
          'Weaker than covalent bond but stronger than Van der Waals forces.',
        ],
      },
    ],
  },

  'States of Matter - Gases and Liquids (FA ONLY)': {
    intro: 'Gas Laws, Kinetic Theory and Properties of Liquids',
    sections: [
      {
        title: 'Intermolecular Forces',
        bullets: [
          'London dispersion forces: weakest, present in all molecules, due to temporary dipoles.',
          'Dipole-dipole forces: between polar molecules.',
          'Dipole-induced dipole: polar molecule induces dipole in non-polar molecule.',
          'Hydrogen bonding: strongest intermolecular force.',
        ],
      },
      {
        title: 'Gas Laws',
        table: {
          headers: ['Law', 'Statement', 'Formula'],
          rows: [
            ["Boyle's Law", 'T constant: P inversely proportional to V', '$PV = $ constant'],
            ["Charles' Law", 'P constant: V directly proportional to T', '$V/T = $ constant'],
            ["Gay-Lussac's Law", 'V constant: P directly proportional to T', '$P/T = $ constant'],
            ["Avogadro's Law", 'Equal volumes at same T, P have equal moles', '$V \\propto n$'],
          ],
        },
      },
      {
        title: 'Ideal Gas Equation',
        content: '$$PV = nRT$$ where $R = 8.314$ J mol$^{-1}$ K$^{-1}$. Combined gas law: $$\\frac{P_1V_1}{T_1} = \\frac{P_2V_2}{T_2}$$',
      },
      {
        title: 'Dalton\'s Law of Partial Pressures',
        content: '$$P_{total} = P_1 + P_2 + P_3 + \\cdots$$ Partial pressure: $P_i = \\chi_i \\times P_{total}$',
      },
      {
        title: 'Kinetic Molecular Theory of Gases',
        bullets: [
          'Gas molecules are point masses with negligible volume.',
          'No intermolecular attractive forces.',
          'Molecules move randomly; collisions are perfectly elastic.',
          'Average KE is proportional to absolute temperature.',
          'Root mean square speed: $u_{rms} = \\sqrt{3RT/M}$',
        ],
      },
      {
        title: 'Deviation from Ideal Behaviour',
        content: "Real gases deviate from ideal behaviour at high pressure and low temperature. Van der Waals equation: $$\\left(P + \\frac{an^2}{V^2}\\right)(V - nb) = nRT$$ where $a$ = intermolecular attraction, $b$ = volume excluded.",
      },
      {
        title: 'Liquefaction of Gases',
        content: 'Critical temperature ($T_c$): temperature above which gas cannot be liquefied regardless of pressure. Critical pressure ($P_c$): minimum pressure needed to liquefy at $T_c$.',
      },
      {
        title: 'Properties of Liquids',
        bullets: [
          'Vapour pressure: pressure of vapour above liquid at equilibrium; increases with temperature.',
          'Surface tension: force per unit length at liquid surface; decreases with temperature.',
          'Viscosity: resistance to flow; decreases with temperature.',
        ],
      },
    ],
  },

  'Chemical Thermodynamics': {
    intro: 'Thermodynamic Terms, Laws, Enthalpy, Entropy and Gibbs Energy',
    sections: [
      { title: 'Thermodynamics Terms',
        bullets: ['System: specific part of universe under observation.','Surroundings: everything that surrounds the system.','Universe = System + Surroundings.'] },
      { title: 'Types of System',
        bullets: ['Open System: exchanges both matter and energy. e.g. reaction in open test tube.','Closed System: exchanges energy but not matter. e.g. reaction in closed vessel.','Isolated System: exchanges neither energy nor matter. e.g. thermos flask.'] },
      { title: 'Thermodynamic Processes',
        table: { headers: ['Process','Condition'],
          rows: [['Isothermal','$\\Delta T = 0$'],['Adiabatic','$\\Delta q = 0$'],['Isobaric','$\\Delta P = 0$'],['Isochoric','$\\Delta V = 0$'],['Cyclic','$\\Delta U = 0$'],['Reversible','Proceeds infinitely slowly through equilibrium steps.'],['Irreversible','Proceeds rapidly; system cannot achieve equilibrium.']] } },
      { title: 'Extensive vs Intensive Properties',
        bullets: ['Extensive: depend on quantity/size — mass, volume, internal energy, enthalpy, heat capacity.','Intensive: do not depend on quantity — temperature, density, pressure, boiling point, melting point.'] },
      { title: 'State Functions',
        content: 'Variables whose value depends only on state of system (path independent): P, V, T, H, G, U, S, n.' },
      { title: 'Internal Energy (U)',
        content: 'Sum of all kinds of energies possessed by the system. Changes when heat enters/exits or work is done.',
        bullets: ['Standard state: pure form at 1 bar.','$\\Delta U = q + w$ (First Law).'] },
      { title: 'First Law of Thermodynamics',
        content: '"The energy of an isolated system is constant." $$\\Delta U = q + w$$',
        bullets: ['$w = +ve$: work done on system. $w = -ve$: work done by system.','$q = +ve$: heat absorbed by system. $q = -ve$: heat evolved by system.','Work of expansion/compression: $w = -P_{ext}(V_f - V_i)$','Isothermal reversible expansion: $w_{rev} = -2.303nRT\\log\\frac{V_f}{V_i} = -2.303nRT\\log\\frac{P_i}{P_f}$','$C_p - C_v = R$ (for ideal gases)'] },
      { title: 'Enthalpy (H)',
        content: '$$H = U + PV, \\quad \\Delta H = \\Delta U + \\Delta(PV)$$ At constant pressure: $\\Delta H = q_p$.',
        bullets: ['$\\Delta H = \\Delta U + \\Delta n_g RT$ (for gaseous reactions)','$\\Delta H = \\Delta U$ if $\\Delta n_g = 0$ e.g. $H_2 + I_2 \\to 2HI$','$\\Delta H > \\Delta U$ if $\\Delta n_g > 0$ e.g. $PCl_5 \\to PCl_3 + Cl_2$','$\\Delta H < \\Delta U$ if $\\Delta n_g < 0$ e.g. $N_2 + 3H_2 \\to 2NH_3$'] },
      { title: 'Heat Capacity and Calorimetry',
        content: 'Heat capacity $C$: amount of heat to raise temperature of substance by 1°C or 1K. $$q = C\\Delta T$$',
        bullets: ['Specific heat capacity $C_s$: $q = C_s \\times m \\times \\Delta T$','Molar heat capacity $C_m$: $q = C_m \\times n \\times \\Delta T$','Bomb calorimeter: measures $\\Delta U$ at constant volume ($q_V$).','Constant pressure calorimeter: measures $\\Delta H = q_p$.'] },
      { title: 'Standard Enthalpy of Formation ($\\Delta_f H^\\circ$)',
        content: 'Enthalpy change when 1 mole of compound forms from its elements in standard states (298 K, 1 bar).',
        bullets: ['$\\Delta_f H^\\circ$ of element in standard state = zero.','Compounds with $-ve$ $\\Delta_f H^\\circ$ are more stable.','$\\Delta_r H^\\circ = \\sum a_i\\Delta_f H^\\circ(\\text{products}) - \\sum b_i\\Delta_f H^\\circ(\\text{reactants})$','Example: $H_2(g) + \\frac{1}{2}O_2(g) \\to H_2O(l)$; $\\Delta H_f^\\circ = -285.8$ kJ/mol','Example: $C(graphite) + 2H_2(g) \\to CH_4(g)$; $\\Delta H_f^\\circ = -74.81$ kJ/mol'] },
      { title: 'Standard Enthalpy of Combustion ($\\Delta_c H^\\circ$)',
        content: 'Enthalpy change on complete combustion of 1 mole at standard conditions. Always exothermic.',
        bullets: ['Butane: $C_4H_{10}(g) + \\frac{13}{2}O_2(g) \\to 4CO_2(g) + 5H_2O(l)$; $\\Delta_c H^\\circ = -2658$ kJ/mol'] },
      { title: "Hess's Law",
        content: 'Total enthalpy change of a reaction remains same whether in one step or several steps. Standard reaction enthalpy = sum of individual step enthalpies.' },
      { title: 'Bond Enthalpy',
        content: 'Enthalpy change when 1 mole of gaseous covalent bond is broken to form gaseous products. $$\\Delta_r H^\\circ = \\sum \\Delta_{bond}H^\\circ(\\text{reactants}) - \\sum \\Delta_{bond}H^\\circ(\\text{products})$$',
        bullets: ['$Cl_2(g) \\to 2Cl(g)$; $\\Delta H^\\circ = 242$ kJ/mol','Diatomic: bond enthalpy = bond dissociation enthalpy = atomization enthalpy.'] },
      { title: 'Entropy (S)',
        content: 'Measure of degree of randomness/disorder of system. $$\\Delta S_{sys} = \\frac{q_{rev}}{T}$$ Unit: J K$^{-1}$ mol$^{-1}$',
        bullets: ['Second Law: $\\Delta S_{total} = \\Delta S_{sys} + \\Delta S_{surr} > 0$ for spontaneous process.','Third Law: Entropy of perfectly crystalline solid at 0 K = zero.','Entropy increases: solid → liquid → gas.'] },
      { title: 'Gibbs Energy and Spontaneity',
        content: '$$G = H - TS, \\quad \\Delta G = \\Delta H - T\\Delta S$$',
        table: { headers: ['$\\Delta H$','$\\Delta S$','$\\Delta G$','Spontaneity'],
          rows: [['$-$','$+$','Always $-$','Always spontaneous'],['$+$','$-$','Always $+$','Never spontaneous'],['$-$','$-$','Depends on T','Spontaneous at low T'],['$+$','$+$','Depends on T','Spontaneous at high T']] } },
      { title: 'Gibbs Energy and Equilibrium Constant',
        content: '$$\\Delta G^\\circ = -RT\\ln K = -2.303RT\\log K$$',
        bullets: ['$\\Delta G = 0$: equilibrium.','$\\Delta G^\\circ < 0 \\Rightarrow K > 1$: products favoured.','$\\Delta G^\\circ > 0 \\Rightarrow K < 1$: reactants favoured.','Endothermic reactions: $\\Delta H^\\circ$ large positive, $K < 1$.','Exothermic reactions: $\\Delta H^\\circ$ large negative, $K > 1$.'] },
    ],
  },

  'Equilibrium': {
    intro: 'Chemical and Ionic Equilibrium, Le Chatelier Principle',
    sections: [
      { title: 'Equilibrium in Physical Processes',
        content: 'Equilibrium: state where two opposing processes occur simultaneously at same rate. $\\Delta G = 0$ at equilibrium.',
        bullets: ['Solid-liquid: ice and water at 273 K show dynamic activity at boundaries.','Liquid-vapour: evaporation = condensation rates at constant pressure.','Solid-vapour: e.g. iodine and camphor sublimation.','Henry\'s Law: gas solubility decreases with temperature; increases with pressure.'] },
      { title: 'Equilibrium in Chemical Processes',
        content: 'Dynamic equilibrium: rate of forward reaction = rate of reverse reaction. Reached from either direction.',
        bullets: ['Haber process: $N_2(g) + 3H_2(g) \\rightleftharpoons 2NH_3(g)$','Concentrations of reactants and products remain constant at equilibrium.','Demonstrated by isotope scrambling — mixing $(H_2, N_2, NH_3)$ and $(D_2, N_2, ND_3)$.'] },
      { title: 'Equilibrium Constant',
        content: 'For $aA + bB \\rightleftharpoons cC + dD$: $$K_c = \\frac{[C]^c[D]^d}{[A]^a[B]^b}, \\quad K_p = \\frac{P_C^c \\cdot P_D^d}{P_A^a \\cdot P_B^b}$$',
        table: { headers: ['Chemical Equation','Equilibrium Constant'],
          rows: [['$aA + bB \\rightleftharpoons cC + dD$','$K$'],['$cC + dD \\rightleftharpoons aA + bB$','$K_1 = 1/K$'],['$naA + nbB \\rightleftharpoons ncC + ndD$','$K_2 = K^n$'],['$\\frac{1}{n}aA + \\frac{1}{n}bB \\rightleftharpoons \\frac{1}{n}cC + \\frac{1}{n}dD$','$K_3 = K^{1/n}$']] } },
      { title: 'Relation Between $K_p$ and $K_c$',
        content: '$$K_p = K_c(RT)^{\\Delta n_g}$$ where $\\Delta n_g = n_p(g) - n_r(g)$.' },
      { title: 'Predicting Reaction Direction',
        bullets: ['Reaction quotient $Q_c$ calculated like $K_c$ but with non-equilibrium concentrations.','$Q_c = K_c$: system at equilibrium.','$Q_c > K_c$: reaction proceeds in reverse direction.','$Q_c < K_c$: reaction proceeds in forward direction.'] },
      { title: 'Applications of Equilibrium Constants',
        bullets: ['Predict extent of reaction: high $K_c$ → products predominant; low $K_c$ → reactants predominant.','$K_c$ in range $10^{-3}$ to $10^3$: appreciable amounts of both reactants and products.','Calculate equilibrium concentrations using ICE table (Initial, Change, Equilibrium).'] },
      { title: 'Homogeneous Equilibria',
        bullets: ['All reactants and products in same phase.','Example: $N_2(g) + 3H_2(g) \\rightleftharpoons 2NH_3(g)$ — all gaseous.','$K_p$ for $N_2 + 3H_2 \\rightleftharpoons 2NH_3$: at 298 K = $6.8 \\times 10^3$; 400 K = 41; 500 K = $3.6 \\times 10^3$.'] },
      { title: 'Heterogeneous Equilibria',
        content: 'Equilibrium involving more than one phase. Pure solids and liquids have constant molar concentrations and are excluded from $K$ expression.',
        bullets: ['$CaCO_3(s) \\rightleftharpoons CaO(s) + CO_2(g)$: $K_p = p_{CO_2}$','$Ca(OH)_2(s) \\rightleftharpoons Ca^{2+}(aq) + 2OH^-(aq)$','$Ni(s) + 4CO(g) \\rightleftharpoons Ni(CO)_4(g)$'] },
      { title: "Le Chatelier's Principle",
        content: 'When equilibrium is disturbed by change in T, P or concentration, it shifts to counteract the change.',
        table: { headers: ['Change at Equilibrium','Shift in Equilibrium'],
          rows: [['Increase temperature','Endothermic direction'],['Decrease temperature','Exothermic direction'],['Increase pressure','Towards fewer moles of gas'],['Decrease pressure','Towards more moles of gas'],['Increase conc. of reactants','Forward direction'],['Increase conc. of products','Reverse direction']] } },
      { title: "Le Chatelier's — Catalyst and Inert Gas",
        bullets: ['Catalyst: increases rate of both forward and reverse reactions equally; does not shift equilibrium position.','Inert gas at constant volume: does not alter equilibrium concentrations.','Exothermic reactions: $K$ decreases with temperature increase.','Endothermic reactions: $K$ increases with temperature increase.'] },
      { title: 'Ionic Equilibrium and Electrolytes',
        bullets: ['Strong electrolytes: almost completely ionised (HCl, NaOH, NaCl).','Weak electrolytes: partially ionised (CH₃COOH, NH₄OH) — establish equilibrium.','Ionic product of water: $K_w = [H_3O^+][OH^-] = 10^{-14}$ at 298 K.'] },
      { title: 'Acids, Bases and pH',
        content: '$$\\text{pH} = -\\log[H^+], \\quad \\text{pOH} = -\\log[OH^-], \\quad \\text{pH} + \\text{pOH} = 14 \\text{ (at 298 K)}$$',
        bullets: ['pH < 7: acidic. pH = 7: neutral. pH > 7: basic.','Conjugate acid-base pairs differ by one $H^+$.','$K_w = K_a \\times K_b$','Ostwald\'s dilution law: $\\alpha = \\sqrt{K_a/C}$ (for weak electrolyte)'] },
      { title: 'Hydrolysis of Salts',
        table: { headers: ['Salt type','Example','Hydrolysis','pH'],
          rows: [['Strong acid + Strong base','NaCl','No hydrolysis','7'],['Weak acid + Strong base','CH₃COONa','Anion hydrolyses','> 7'],['Strong acid + Weak base','NH₄Cl','Cation hydrolyses','< 7'],['Weak acid + Weak base','CH₃COONH₄','Both hydrolyse','depends on $K_a, K_b$']] } },
      { title: 'Buffer Solutions',
        content: 'Resist change in pH on dilution or on addition of small amounts of acid or base.',
        bullets: ['Acidic buffer: weak acid + salt with strong base. e.g. CH₃COOH + CH₃COONa.','Basic buffer: weak base + salt with strong acid. e.g. NH₄OH + NH₄Cl.','Henderson-Hasselbalch: $\\text{pH} = pK_a + \\log\\frac{[\\text{Salt}]}{[\\text{Acid}]}$'] },
      { title: 'Solubility Product ($K_{sp}$)',
        content: 'For $A_xB_y \\rightleftharpoons xA^{y+} + yB^{x-}$: $$K_{sp} = [A^{y+}]^x[B^{x-}]^y = x^x \\cdot y^y \\cdot s^{(x+y)}$$',
        bullets: ['Binary salt (e.g. AgCl): $K_{sp} = s^2$','Ternary salt (e.g. $PbI_2$): $K_{sp} = 4s^3$','Ionic product $< K_{sp}$: salt remains dissolved.','Ionic product $> K_{sp}$: salt precipitates.','Soluble: $>0.1$ M. Slightly soluble: $0.01-0.1$ M. Sparingly soluble: $<0.01$ M.'] },
    ],
  },

  'Redox Reactions': {
    intro: 'Oxidation, Reduction, Oxidation Number and Electrochemistry',
    sections: [
      { title: 'Classical Oxidation and Reduction',
        table: { headers: ['Oxidation','Reduction'],
          rows: [['Addition of oxygen','Removal of oxygen'],['Removal of hydrogen','Addition of hydrogen'],['Addition of electronegative element','Removal of electronegative element'],['Removal of electropositive element','Addition of electropositive element'],['Loss of electron(s)','Gain of electron(s)'],['Increase in oxidation number','Decrease in oxidation number']] } },
      { title: 'Oxidising and Reducing Agents',
        bullets: ['Reducing agent: reduces other substance and oxidises itself (electron donor).','Oxidising agent: oxidises other substance and reduces itself (electron acceptor).','Redox reaction: oxidation and reduction take place simultaneously.'] },
      { title: 'Types of Redox Reactions',
        bullets: ['Combination: $3Mg(s) + N_2(g) \\to Mg_3N_2(s)$','Decomposition: $2KClO_3 \\to 2KCl + 3O_2$','Metal displacement: $CuSO_4(aq) + Zn(s) \\to ZnSO_4(aq) + Cu(s)$','Non-metal displacement: $Ca(s) + 2H_2O(l) \\to Ca(OH)_2 + H_2(g)$','Disproportionation: same element oxidised and reduced simultaneously. $Cl_2(g) + 2OH^-(aq) \\to Cl^-(aq) + ClO^-(aq) + H_2O(l)$'] },
      { title: 'Oxidation Number Rules',
        bullets: ['Free elements in standard state: O.S. = 0 (e.g. $Cl_2, O_2, P_4, Fe, N_2$).','Group 1 elements: +1. Group 2 elements: +2.','Monoatomic ion: O.S. = charge of ion.','Oxygen: usually $-2$; in peroxides ($H_2O_2, Na_2O_2$) = $-1$; in $OF_2$ = $+2$; in $KO_2$ (superoxide) = $-\\frac{1}{2}$.','Hydrogen: +1 (usually); $-1$ in metal hydrides.','Fluorine: always $-1$.','Sum of O.S. in neutral compound = 0; in polyatomic ion = charge on ion.'] },
      { title: 'Fractional Oxidation Number',
        content: 'When two or more atoms of same element are in different oxidation states, calculated O.S. may be fractional (average). In reality no element has fractional O.S.' },
      { title: 'Balancing Redox Reactions',
        bullets: ['(A) Oxidation number method: assign O.S., identify changes, balance by arithmetic.','(B) Half-reaction method: split into oxidation and reduction half-equations, balance atoms (H₂O for O, H⁺ for H in acidic medium), balance charges, equalise electrons, add half-reactions.'] },
      { title: 'Redox Reactions and Electrode Processes',
        content: 'Stock notation: oxidation state of metal shown in Roman numerals in parenthesis. e.g. Fe₂(III)O₃ = Iron(III) oxide.',
        bullets: ['Electrode potential (E): potential difference between electrode and electrolytic solution.','Standard electrode potential ($E^\\circ$): measured at 298 K, 1M concentration (or 1 bar for gas).','Electrochemical cell: chemical energy of spontaneous redox reaction → electrical energy.'] },
      { title: 'Daniel Cell',
        content: 'Cell diagram: $Zn | Zn^{2+} || Cu^{2+} | Cu$',
        table: { headers: ['','Left Electrode (Anode)','Right Electrode (Cathode)'],
          rows: [['Process','Oxidation: $Zn \\to Zn^{2+} + 2e^-$','Reduction: $Cu^{2+} + 2e^- \\to Cu$'],['Sign','Negative','Positive'],['Overall','$Zn(s) + Cu^{2+}(aq) \\to Zn^{2+}(aq) + Cu(s)$','']] } },
      { title: 'Functions of Salt Bridge',
        bullets: ['Completes the inner circuit.','Maintains electrical neutrality around electrodes.'] },
      { title: 'Electron Transfer Series',
        bullets: ['Zinc has stronger tendency to release electrons than copper.','Copper releases electrons more than silver. Order: Zn > Cu > Ag.','Metal activity series ranks metals by ability to release electrons.','Negative $E^\\circ$: stronger reducing agent than $H^+/H_2$.','Positive $E^\\circ$: weaker reducing agent.'] },
    ],
  },

  'The s-Block Elements (FA ONLY)': {
    intro: 'Alkali Metals (Group 1) and Alkaline Earth Metals (Group 2)',
    sections: [
      { title: 'Group 1 Elements: Alkali Metals',
        content: 'Li, Na, K, Rb, Cs, Fr. Outer electronic configuration: $ns^1$. Highly electropositive.',
        bullets: ['Largest atomic sizes in their periods; size increases from Li to Cs.','Low ionisation enthalpies — decreases down the group.','Hydration enthalpy decreases with increasing ionic size; $Li^+$ has maximum hydration.','Soft, silvery-white, low density, low melting/boiling points.','Flame colours: Li-crimson, Na-golden yellow, K-violet, Rb-reddish violet, Cs-blue.','Stored in kerosene to prevent reaction with air/moisture.'] },
      { title: 'Chemical Reactivity of Alkali Metals',
        bullets: ['Reactivity with Air: $4Li + O_2 \\to 2Li_2O$; $2Na + O_2 \\to Na_2O_2$; heavier metals form superoxides.','Reactivity with Water: $2M + 2H_2O \\to 2MOH + H_2$; increases down group.','Reactivity with Halogens: form ionic halides; Li halides show covalent character.','Reducing power: strongest is Li (highest negative $E^\\circ$ due to high hydration energy).','Solutions in liquid ammonia: conducting blue solutions (solvated electrons).'] },
      { title: 'Compounds of Sodium',
        table: { headers: ['Compound','Formula','Uses'],
          rows: [['Sodium chloride (table salt)','NaCl','Food, chemical industry'],['Sodium hydroxide (caustic soda)','NaOH','Soap, paper, textiles, water treatment'],['Sodium carbonate (washing soda)','Na\u2082CO\u2083\u00b710H\u2082O','Glass, water softening, detergents'],['Sodium bicarbonate (baking soda)','NaHCO\u2083','Baking, medicine, fire extinguishers'],['Sodium peroxide','Na\u2082O\u2082','Oxidising agent, O\u2082 generation'],['Sodium thiosulfate','Na\u2082S\u2082O\u2083','Photography fixer, cyanide antidote']] } },
      { title: 'Anomalous Properties of Lithium',
        bullets: ['Small size and high polarising power: hardest alkali metal with highest mp/bp.','Least reactive but strongest reducing agent.','Forms $Li_2O$ and $Li_3N$ in air; LiCl crystallises as $LiCl \\cdot 2H_2O$.','Does not form solid hydrogencarbonate.','Diagonal relationship with Mg.'] },
      { title: 'Biological Importance of Na and K',
        bullets: ['Maintain fluid balance, osmotic pressure and acid-base equilibrium.','Na$^+$ (extracellular): regulates blood volume; generates action potentials.','K$^+$ (intracellular): enzyme activation, protein synthesis, photosynthesis.','Sodium-potassium pump maintains electrochemical gradient.'] },
      { title: 'Group 2 Elements: Alkaline Earth Metals',
        content: 'Be, Mg, Ca, Sr, Ba, Ra. Configuration: $ns^2$.',
        bullets: ['Harder and denser than Group 1; less reactive.','React with water (except Be and Mg in cold): $M + 2H_2O \\to M(OH)_2 + H_2$','Flame colours: Ca-brick red, Sr-crimson, Ba-apple green.','Be: does not react with water, covalent compounds, amphoteric oxide (diagonal relationship with Al).'] },
      { title: 'Important Compounds of Calcium',
        table: { headers: ['Compound','Formula','Uses'],
          rows: [['Quicklime','CaO','Cement, steel, disinfectant'],['Slaked lime','Ca(OH)\u2082','Mortar, whitewash, water treatment'],['Limestone/Marble','CaCO\u2083','Building material, cement'],['Plaster of Paris','CaSO\u2084\u00b7\u00bdH\u2082O','Surgical casts, wall plaster'],['Gypsum','CaSO\u2084\u00b72H\u2082O','Cement retarder, fertiliser']] } },
    ],
  },

  'Some p-Block Elements (FA ONLY)': {
    intro: 'Group 13 (Boron Family) and Group 14 (Carbon Family)',
    sections: [
      { title: 'Group 13 Elements: The Boron Family',
        content: 'B, Al, Ga, In, Tl. Configuration: $ns^2np^1$.',
        bullets: ['B: non-metallic, hard. Al: most abundant metal in earth\'s crust.','Atomic radius: Ga < Al (poor shielding by d-electrons).','BF\u2083: Lewis acid (electron deficient). Al: amphoteric.','Ga, In, Tl: +1 and +3 oxidation states (inert pair effect).'] },
      { title: 'Reactions of Group 13',
        bullets: ['$2Al + 6HCl \\to 2AlCl_3 + 3H_2$ (with acids)','$2Al + 2NaOH + 2H_2O \\to 2NaAlO_2 + 3H_2$ (with alkalis)','Thermite reaction: $Fe_2O_3 + 2Al \\to Al_2O_3 + 2Fe$ (welding)','Trihalides: covalent, undergo hydrolysis with water.','Diborane ($B_2H_6$): banana bonds (3c-2e bonds). Borax ($Na_2B_4O_7 \\cdot 10H_2O$).'] },
      { title: 'Group 14 Elements: The Carbon Family',
        content: 'C, Si, Ge, Sn, Pb. Configuration: $ns^2np^2$.',
        bullets: ['C: non-metal. Si, Ge: metalloids. Sn, Pb: metals.','Carbon: unique catenation and formation of multiple bonds.','Inert pair effect: Pb\u00b2\u207a more stable than Pb\u2074\u207a.'] },
      { title: 'Allotropes of Carbon',
        bullets: ['Diamond: 3D tetrahedral, sp\u00b3, extremely hard, insulator.','Graphite: layered hexagonal, sp\u00b2, soft, good electrical conductor.','Fullerene (C\u2086\u2080): unique electronic properties.','Graphene: exceptional mechanical and electrical properties.'] },
      { title: 'Important Compounds of Carbon and Silicon',
        bullets: ['CO\u2082: greenhouse gas; essential for photosynthesis.','CO: metallurgical processes.','CaC\u2082 (calcium carbide): industrially significant.','SiO\u2082: glass, ceramics, electronics. Silicones: lubricants, sealants. SiC: abrasive.','Silicates: basic unit $[SiO_4]^{4-}$ tetrahedron; major constituents of rocks.'] },
    ],
  },

  'Organic Chemistry Some Basic Principles and Techniques': {
    intro: 'Tetravalency, Classification, Nomenclature and Purification',
    sections: [
      { title: 'Tetravalence of Carbon: Shapes of Organic Compounds',
        table: { headers: ['Hybridisation','Structure','Bond Angle','Examples'],
          rows: [['$sp^3$','Tetrahedral','109\u00b028\'','Methane, Ethane'],['$sp^2$','Trigonal planar','120\u00b0','Ethene, Propene'],['$sp$','Linear','180\u00b0','Ethyne, Propyne']] } },
      { title: 'Reasons for Large Number of Organic Compounds',
        bullets: ['Catenation: carbon links with itself to form chains.','Isomerism: same molecular formula, different properties.','Multiple bonds: double and triple bonds possible.','First organic compound: urea by Wöhler from $NH_4CNO \\xrightarrow{\\Delta} NH_2CONH_2$.'] },
      { title: 'Homologous Series',
        table: { headers: ['Series','General Formula'],
          rows: [['Alkanes','$C_nH_{2n+2}$'],['Alkenes','$C_nH_{2n}$'],['Alkynes','$C_nH_{2n-2}$'],['Alcohol/Ether','$C_nH_{2n+2}O$'],['Aldehyde/Ketone','$C_nH_{2n}O$'],['Acid/Ester','$C_nH_{2n}O_2$']] } },
      { title: 'Classification of Organic Compounds',
        bullets: ['Acyclic (aliphatic): open chain.','Cyclic: alicyclic (carbocyclic rings) or aromatic (benzene ring).','Carbon types: 1\u00b0 (1C attached), 2\u00b0 (2C), 3\u00b0 (3C), 4\u00b0 (4C).'] },
      { title: 'Functional Groups',
        table: { headers: ['Class','Functional Group','Suffix'],
          rows: [['Alcohol','$-OH$','-ol'],['Aldehyde','$-CHO$','-al'],['Ketone','$>C=O$','-one'],['Carboxylic acid','$-COOH$','-oic acid'],['Ester','$-COOR$','-alkanoate'],['Amine','$-NH_2$','-amine'],['Nitrile','$-CN$','-nitrile']] } },
      { title: 'IUPAC Nomenclature',
        content: 'Word roots: Meth(C1), Eth(C2), Prop(C3), But(C4), Pent(C5), Hex(C6), Hept(C7), Oct(C8), Non(C9), Dec(C10).',
        bullets: ['Rule 1: longest chain containing principal functional group.','Rule 2: lowest number to principal functional group; branching gets lowest number.','Priority: $-COOH > -CHO > C=O > -OH > -NH_2$','Primary suffix: -ane, -ene, -yne.'] },
      { title: 'Isomerism',
        bullets: ['Structural: same molecular formula, different structure.','Chain, position, functional group, metamerism.','Stereo: same connectivity, different 3D arrangement.','Geometrical (cis-trans): restricted rotation at C=C.','Optical: non-superimposable mirror images; require chiral centre.'] },
      { title: 'Electronic Effects',
        bullets: ['Inductive ($-I$): electron withdrawing — $-NO_2, -CN, -F, -Cl$. $(+I)$: donating — alkyl groups.','Resonance: delocalisation; hybrid more stable than any single structure.','Hyperconjugation: $\\sigma$ electrons of C-H adjacent to $\\pi$ bond — more $\\alpha$-H → more stability.'] },
      { title: 'Purification Methods',
        table: { headers: ['Method','Used For'],
          rows: [['Sublimation','Naphthalene, camphor, iodine'],['Crystallisation','Purifying solids'],['Distillation','Volatile liquids from non-volatile impurities'],['Fractional distillation','Liquids with close boiling points'],['Steam distillation','Steam-volatile, water-immiscible compounds'],['Chromatography','Amino acids, sugars, drugs, pigments']] } },
      { title: 'Qualitative Analysis (Lassaigne\'s Test)',
        table: { headers: ['Element','Positive Test'],
          rows: [['C and H','CO\u2082 turns lime water milky; water turns anhydrous CuSO\u2084 blue'],['N','Prussian blue with FeCl\u2083'],['S','Deep violet with sodium nitroprusside; black ppt with Pb acetate'],['N + S','Blood red (thiocyanate) with FeCl\u2083'],['Cl','White ppt AgCl (soluble in NH\u2083)'],['Br','Yellow ppt AgBr (partially soluble in NH\u2083)'],['I','Yellow ppt AgI (insoluble in NH\u2083)'],['P','Yellow ppt with ammonium molybdate']] } },
      { title: 'Quantitative Analysis Formulas',
        bullets: ['$\\%C = \\frac{12}{44} \\times \\frac{m_{CO_2}}{m_{compound}} \\times 100$','$\\%H = \\frac{2}{18} \\times \\frac{m_{H_2O}}{m_{compound}} \\times 100$','$\\%N\\text{ (Dumas)} = \\frac{28}{22400} \\times \\frac{V_{N_2}}{m_{compound}} \\times 100$','$\\%N\\text{ (Kjeldahl)} = \\frac{1.4 \\times M \\times V \\times \\text{basicity}}{m_{compound}}$','$\\%X\\text{ (Carius)} = \\frac{\\text{At.mass X}}{108+\\text{At.mass X}} \\times \\frac{m_{AgX}}{m_{compound}} \\times 100$','$\\%S\\text{ (Carius)} = \\frac{32}{233} \\times \\frac{m_{BaSO_4}}{m_{compound}} \\times 100$'] },
    ],
  },

  'Hydrocarbons': {
    intro: 'Alkanes, Alkenes, Alkynes and Aromatic Hydrocarbons',
    sections: [
      { title: 'Classification of Hydrocarbons',
        content: 'Hydrocarbons: organic compounds containing only C and H.',
        bullets: ['Saturated (Alkanes): C-C single bonds only.','Unsaturated (Alkenes, Alkynes): double or triple bonds.','Aromatic (Arenes): benzene ring with special stability.','Uses: LPG, CNG, LNG fuels; solvents; polymers; raw materials for dyes and drugs.'] },
      { title: 'Alkanes — Saturated Hydrocarbons',
        content: 'General formula: $C_nH_{2n+2}$. $sp^3$ hybridised. Bond angle 109.5°. Inert under normal conditions.',
        bullets: ['First 4 (C₁-C₄): gases. C₅-C₁₇: liquids. C₁₈+: solids at 298 K.','Non-polar; soluble in non-polar solvents. Boiling point increases with chain length.','Boiling point decreases on branching (decreased surface area → weaker van der Waals forces).'] },
      { title: 'Preparation of Alkanes',
        bullets: ['Hydrogenation of alkenes/alkynes: $R-CH=CH_2 + H_2 \\xrightarrow{Ni/\\Delta} R-CH_2-CH_3$','Reduction of alkyl halides: $CH_3Cl + H_2 \\xrightarrow{Zn, H^+} CH_4 + HCl$','Wurtz reaction (symmetrical alkanes): $2C_2H_5Br + 2Na \\xrightarrow{dry\\ ether} C_4H_{10} + 2NaBr$','Decarboxylation (soda lime): $CH_3COONa + NaOH \\xrightarrow{CaO, \\Delta} CH_4 + Na_2CO_3$','Kolbe\'s electrolytic method: electrolysis of sodium salt of carboxylic acid; alkane with even carbon atoms at anode.'] },
      { title: 'Chemical Reactions of Alkanes',
        bullets: ['Halogenation (free radical mechanism): $CH_4 + Cl_2 \\xrightarrow{h\\nu} CH_3Cl + HCl$ (then $CH_2Cl_2$, $CHCl_3$, $CCl_4$).','Reactivity: $F_2 > Cl_2 > Br_2 > I_2$. Replacement rate: $3° > 2° > 1°$.','Combustion: $CH_4 + 2O_2 \\to CO_2 + 2H_2O$','Isomerisation: n-butane → isobutane at 200°C, 35 atm, AlCl₃+HCl.','Reaction with steam: $CH_4 + H_2O \\xrightarrow{Ni, \\Delta} CO + 3H_2$','Pyrolysis: decomposition of higher alkanes to lower on heating.'] },
      { title: 'Conformations of Alkanes',
        content: 'Different spatial arrangements due to rotation around C-C single bond. For ethane:',
        bullets: ['Eclipsed form: all H atoms nearest to each other (least stable).','Staggered form: all H atoms farthest apart (most stable).','Energy difference between forms: 12.5 kJ mol$^{-1}$ — easily interconvertible at room temperature.'] },
      { title: 'Alkenes — Unsaturated Hydrocarbons',
        content: 'General formula: $C_nH_{2n}$. $sp^2$ hybridised. Bond angle 120°. Also called olefins.',
        bullets: ['C=C consists of one strong σ bond and one weaker π bond.','Show structural isomerism and geometrical (cis-trans) isomerism.'] },
      { title: 'Preparation of Alkenes',
        bullets: ['From alkynes: partial reduction with Lindlar\'s catalyst.','Dehydrohalogenation of alkyl halides with alcoholic KOH.','From vicinal dihalides + Zn: $CH_2Br-CH_2Br + Zn \\xrightarrow{\\Delta} CH_2=CH_2 + ZnBr_2$','Dehydration of alcohols: $C_2H_5OH \\xrightarrow{conc. H_2SO_4, \\Delta} CH_2=CH_2 + H_2O$'] },
      { title: 'Chemical Reactions of Alkenes',
        bullets: ['Addition of $H_2$ (hydrogenation): $CH_2=CH_2 + H_2 \\xrightarrow{Ni/\\Delta} CH_3-CH_3$','Addition of halogens: $CH_2=CH_2 + Br_2 \\xrightarrow{CCl_4} BrCH_2-CH_2Br$ (decolourises bromine water — test for unsaturation).','Addition of HX: $HI > HBr > HCl$ in reactivity. Markovnikov\'s rule: negative part adds to C with fewer H.','Anti-Markovnikov (peroxide/Kharasch effect): HBr only; H adds to C with fewer H.','Addition of $H_2SO_4$: forms alkyl hydrogensulphate.','Oxidation: Baeyer\'s reagent ($cold\\ dil.\\ KMnO_4$) decolourises — test for unsaturation → glycol.','Acidic $KMnO_4$/$K_2Cr_2O_7$: cleaves alkene to ketone/acid.','Ozonolysis: $O_3$ → ozonide → $Zn/H_2O$ → aldehydes/ketones.','Polymerisation: $n(CH_2=CH_2) \\to (-CH_2-CH_2-)_n$ (polythene).'] },
      { title: 'Alkynes — Triple Bond Hydrocarbons',
        content: 'General formula: $C_nH_{2n-2}$. $sp$ hybridised. Bond angle 180°. H-C-C bond angle 180°. C≡C: 3σ + 2π bonds, bond length 120 pm.',
        bullets: ['First 2 members: gases. C₅-C₁₂: liquids. Higher: solids.','Acetylene has slight garlic odour due to PH₃ and H₂S impurities.','Insoluble in water; soluble in organic solvents.'] },
      { title: 'Preparation of Alkynes',
        bullets: ['From calcium carbide: $CaC_2 + 2H_2O \\to Ca(OH)_2 + C_2H_2$','From vicinal dihalides: double dehydrohalogenation.','From tetrahalides: $Br_2CH-CHBr_2 + 2Zn \\xrightarrow{\\Delta} HC\\equiv CH + 2ZnBr_2$'] },
      { title: 'Chemical Reactions of Alkynes',
        bullets: ['Acidic character: terminal alkynes ($HC \\equiv C-$) acidic due to 50% s-character in sp orbitals. $HC \\equiv CH + Na \\to HC \\equiv C^-Na^+ + \\frac{1}{2}H_2$. Acidity: $HC\\equiv CH > CH_2=CH_2 > CH_3-CH_3$.','Electrophilic addition (less reactive than alkenes — more energy to disturb π cloud). Markovnikov\'s rule applies.','Addition of $H_2$: $CH_3-C\\equiv CH + H_2 \\xrightarrow{Pt/Pd/Ni} CH_3-CH=CH_2 \\xrightarrow{H_2} CH_3CH_2CH_3$','Addition of HX: $CH_3-C\\equiv CH + HBr \\to CH_3-C(Br)=CH_2 \\xrightarrow{HBr} CH_3-CBr_2-CH_3$','Addition of water: $CH_3-C\\equiv CH + HOH \\xrightarrow{333K, Hg^{2+}/H^+} CH_3COCH_3$ (Markovnikov)','Cyclic polymerisation of ethyne: $3C_2H_2 \\xrightarrow{873K, red\\ hot\\ Fe\\ tube} C_6H_6$ (benzene)'] },
      { title: 'Aromatic Hydrocarbons — Benzene',
        content: 'Benzene ($C_6H_6$): hexagonal ring, alternate single and double bonds, all C atoms $sp^2$ hybridised. Planar, bond angle 120°. All C-C bonds equal in length due to complete delocalisation of π electrons.',
        bullets: ['Isolated by Faraday in 1825.','Kekulé\'s structure: alternating single and double bonds.','Stability explained by resonance — delocalised π electrons.','Hückel\'s rule: aromatic if $(4n+2)$ π electrons. Benzene: 6 π electrons ($n=1$) → aromatic.','Prepared: cyclic polymerisation of ethyne, decarboxylation of benzoic acid, reduction of phenol with Zn.','Physical properties: non-polar, colourless liquid, characteristic aroma, immiscible with water, burns with sooty flame.'] },
      { title: 'Chemical Reactions of Benzene — Electrophilic Substitution',
        bullets: ['Mechanism: (1) generation of electrophile, (2) formation of arenium ion intermediate, (3) removal of proton.','Nitration: $C_6H_6 + HNO_3 \\xrightarrow{H_2SO_4} C_6H_5NO_2 + H_2O$','Halogenation: $C_6H_6 + Cl_2 \\xrightarrow{FeCl_3} C_6H_5Cl + HCl$','Sulphonation: $C_6H_6 + H_2SO_4 \\to C_6H_5SO_3H + H_2O$','Friedel-Crafts alkylation: $C_6H_6 + RCl \\xrightarrow{AlCl_3} C_6H_5R + HCl$','Friedel-Crafts acylation: $C_6H_6 + RCOCl \\xrightarrow{AlCl_3} C_6H_5COR + HCl$','Combustion: $2C_6H_6 + 15O_2 \\to 12CO_2 + 6H_2O$'] },
      { title: 'Directing Effects in Electrophilic Substitution',
        table: { headers: ['Group Type','Effect','Directs To','Examples'],
          rows: [['Activating','Electron donating (+R effect)','ortho and para','$-NH_2, -OH, -CH_3, -OCH_3$'],['Deactivating','Electron withdrawing ($-R$ effect)','meta','$-NO_2, -CN, -CHO, -COOH$'],['Deactivating (o/p)','EW by induction, ED by resonance','ortho and para','$-Cl, -Br$']] } },
      { title: 'Carcinogenicity and Toxicity',
        content: 'Benzene and polynuclear hydrocarbons (multiple fused benzene rings) are carcinogenic.',
        bullets: ['Incomplete combustion of tobacco, coal, petroleum forms polynuclear hydrocarbons.','These enter the body, undergo biochemical transformations, and damage DNA → cancer.','Preventive measure: reduce exposure to tobacco smoke and coal emissions.'] },
    ],
  },

};

export default ChemistryNotes;